version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /Users/isen0011/Documents/Postgres/decorum:/var/lib/postgresql/data
  web:
    logging:
      options:
        max-size: 50m
    build: '.'
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: a123
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - '.:/app'
    entrypoint: ["script/_entrypoint.sh"]
    command: >
      bash -c './script/_web_container_setup && ./script/_update && ./script/_server'
