version: '3'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - /Users/isen0011/Documents/Postgres/decorum:/var/lib/postgresql/data
  selenium:
    image: seleniarm/standalone-chromium:4.17.0
    logging:
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    links:
       - web
    ports:
      - 4444:4444
    shm_size: '256mb'
    volumes:
      - './tmp/selenium_downloads:/home/seluser/Downloads'
  web:
    logging:
      options:
        max-size: 50m
    build: '.'
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: a123
      SELENIUM_DRIVER_URL: "http://selenium:4444/wd/hub"
    env_file: ".env"
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - '.:/app'
    entrypoint: ["script/_entrypoint.sh"]
    command: >
      bash -c './script/_web_container_setup && ./script/_update && ./script/_server'
