#!/bin/sh

# script/_bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
brew update

brew bundle check >/dev/null 2>&1  || {
  echo "==> Installing Homebrew dependencies…"
    brew bundle
}
fi

if [ -f ".overcommit.yml" ]; then
echo "==> Installing Overcommit hooks…"
bundle exec overcommit
bundle exec overcommit --sign
fi

if [ ! -f "./config/initializers/local.rb" ] && [ -z "$RAILS_ENV" ]; then
echo "==> Configuring local development environment variables…"
echo "ENV[\"STUB_INTERNET_ID\"] = \"$USER\"" > ./config/initializers/local.rb
fi
