#!/bin/bash

set -e

cd "$(dirname "$0")/.."

# echo "==> loading the schema"
# RAILS_ENV=development bin/rake db:schema:load
# RAILS_ENV=test bin/rake db:schema:load
# 
# echo "==> running the migrations"
# RAILS_ENV=development bin/rails db:migrate
# RAILS_ENV=test bin/rails db:migrate
# 
# echo "==> seeding database"
# RAILS_ENV=development bin/rails db:seed
# RAILS_ENV=test bin/rails db:seed
