#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
RAILS_ENV=development bin/rails s -b 0.0.0.0
