#!/bin/bash

# script/_setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
#               intended to be run in the container

USER=$1

