#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  bundle exec rspec "$1"
else
  bundle exec rspec
fi
