#!/bin/sh

# script/_update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

# clean and rebuild the database

script/_rebuild_database

echo "==> Database ready!"
