#!/bin/sh

# script/_web_container_setup
# Configures the web server container. To be used both for local docker development and CI container setup.

if [ -f "yarn.lock" ]; then
echo "==> Installing yarn packages…"
yarn --development
fi
